version: '3'

services:
  backend:
    image: grammatically_backend
    depends_on:
      - postgres
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./docker/.env

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
