version: '3.1'

services:
  backend:
    image: grammatically_backend
    restart: always
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run db:refresh && npm run start'
    depends_on:
      - postgres
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./docker/.env

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=grammatically
      - POSTGRES_DB=grammatically
    ports:
      - 5555:5432
